# Generated by Django 5.0.3 on 2026-04-17 02:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('konten_html', models.TextField()),
                ('jenis', models.CharField(choices=[('BERITA', 'BERITA'), ('PENGUMUMAN', 'PENGUMUMAN')], default='BERITA', max_length=20)),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publikasi_informasi',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
