# Generated by Django 5.0.3 on 2026-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikasi_informasi', '0002_alter_publikasi_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi',
            name='jenis',
            field=models.CharField(choices=[('BERITA', 'BERITA'), ('PENGUMUMAN', 'PENGUMUMAN')], default='BERITA', max_length=20),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT', max_length=20),
        ),
    ]
