# Generated by Django 5.0.3 on 2026-04-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikasi_informasi', '0003_alter_publikasi_jenis_alter_publikasi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi',
            name='jenis',
            field=models.CharField(choices=[('PENGUMUMAN', 'PENGUMUMAN'), ('BERITA', 'BERITA')], default='BERITA', max_length=20),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=20),
        ),
    ]
