# Generated by Django 5.0.3 on 2026-04-16 14:19

import django.utils.timezone
import toolbox.storage.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BumdesUnitUsaha',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_usaha', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('KOPERASI', 'KOPERASI'), ('JASA', 'JASA'), ('WISATA', 'WISATA')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('fasilitas', models.TextField(blank=True, null=True)),
                ('kontak_wa', models.CharField(blank=True, max_length=20, null=True)),
                ('harga_tiket', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('foto_utama', models.ImageField(blank=True, null=True, upload_to=toolbox.storage.paths.bumdes_media_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bumdes_unit_usaha',
                'ordering': ['-created_at'],
            },
        ),
    ]
