# Generated by Django 5.0.3 on 2026-04-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potensi_ekonomi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumdesunitusaha',
            name='kategori',
            field=models.CharField(choices=[('WISATA', 'WISATA'), ('JASA', 'JASA'), ('KOPERASI', 'KOPERASI')], max_length=50),
        ),
    ]
