# Generated by Django 5.0.3 on 2026-04-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potensi_ekonomi', '0002_alter_bumdesunitusaha_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumdesunitusaha',
            name='kategori',
            field=models.CharField(choices=[('WISATA', 'WISATA'), ('KOPERASI', 'KOPERASI'), ('JASA', 'JASA')], max_length=50),
        ),
    ]
