# Generated by Django 5.0.3 on 2026-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potensi_ekonomi', '0003_alter_bumdesunitusaha_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumdesunitusaha',
            name='kategori',
            field=models.CharField(choices=[('JASA', 'JASA'), ('WISATA', 'WISATA'), ('KOPERASI', 'KOPERASI')], max_length=50),
        ),
    ]
