from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomepageContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tagline", models.CharField(blank=True, default="", max_length=255)),
                ("hero_image", models.URLField(blank=True, default="")),
                ("hero_badge", models.CharField(blank=True, default="", max_length=100)),
                ("brand_logo_url", models.URLField(blank=True, default="")),
                ("brand_logo_alt", models.CharField(blank=True, default="", max_length=150)),
                ("brand_region_label", models.CharField(blank=True, default="", max_length=150)),
                ("village_name", models.CharField(blank=True, default="", max_length=150)),
                ("hero_description", models.TextField(blank=True, default="")),
                ("contact_address", models.TextField(blank=True, default="")),
                ("contact_whatsapp", models.CharField(blank=True, default="", max_length=30)),
                ("contact_map_image", models.URLField(blank=True, default="")),
                ("quick_stats_description", models.TextField(blank=True, default="")),
                ("naming_title", models.CharField(blank=True, default="", max_length=255)),
                ("naming_description", models.TextField(blank=True, default="")),
                ("naming_image", models.URLField(blank=True, default="")),
                ("naming_quote", models.TextField(blank=True, default="")),
                ("culture_title", models.CharField(blank=True, default="", max_length=255)),
                ("culture_description", models.TextField(blank=True, default="")),
                ("sialang_title", models.CharField(blank=True, default="", max_length=255)),
                ("sialang_description", models.TextField(blank=True, default="")),
                ("sialang_image", models.URLField(blank=True, default="")),
                ("sialang_badge", models.CharField(blank=True, default="", max_length=100)),
                ("sialang_stat", models.CharField(blank=True, default="", max_length=120)),
                ("sialang_quote", models.TextField(blank=True, default="")),
                ("peat_title", models.CharField(blank=True, default="", max_length=255)),
                ("peat_description", models.TextField(blank=True, default="")),
                ("peat_quote", models.TextField(blank=True, default="")),
                ("peat_images", models.JSONField(blank=True, default=list)),
                ("potential_quote", models.TextField(blank=True, default="")),
                ("facilities_title", models.CharField(blank=True, default="", max_length=255)),
                ("footer_description", models.TextField(blank=True, default="")),
                ("footer_badges", models.JSONField(blank=True, default=list)),
                ("footer_copyright", models.CharField(blank=True, default="", max_length=255)),
                ("office_hours", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "homepage_content"},
        ),
        migrations.CreateModel(
            name="HomepageCultureCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("icon", models.CharField(blank=True, default="", max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("homepage", models.ForeignKey(on_delete=models.deletion.CASCADE, to="homepage_konten.homepagecontent")),
            ],
            options={"db_table": "homepage_culture_card", "ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="HomepageRecoveryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("icon", models.CharField(blank=True, default="", max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("wrapper", models.CharField(blank=True, default="", max_length=150)),
                ("homepage", models.ForeignKey(on_delete=models.deletion.CASCADE, to="homepage_konten.homepagecontent")),
            ],
            options={"db_table": "homepage_recovery_item", "ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="HomepagePotentialOpportunityItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("icon", models.CharField(blank=True, default="", max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("homepage", models.ForeignKey(on_delete=models.deletion.CASCADE, to="homepage_konten.homepagecontent")),
            ],
            options={"db_table": "homepage_potential_opportunity_item", "ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="HomepageFacility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("icon", models.CharField(blank=True, default="", max_length=100)),
                ("label", models.CharField(max_length=150)),
                ("homepage", models.ForeignKey(on_delete=models.deletion.CASCADE, to="homepage_konten.homepagecontent")),
            ],
            options={"db_table": "homepage_facility", "ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="HomepageGalleryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.URLField()),
                ("alt", models.CharField(max_length=150)),
                ("tall", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("homepage", models.ForeignKey(on_delete=models.deletion.CASCADE, to="homepage_konten.homepagecontent")),
            ],
            options={"db_table": "homepage_gallery_item", "ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="HomepageFooterLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=100)),
                ("href", models.CharField(max_length=255)),
                ("homepage", models.ForeignKey(on_delete=models.deletion.CASCADE, to="homepage_konten.homepagecontent")),
            ],
            options={"db_table": "homepage_footer_link", "ordering": ["sort_order", "id"]},
        ),
    ]
