# Generated by Django 5.0.3 on 2026-04-16 11:28

import django.db.models.deletion
import django.utils.timezone
import toolbox.storage.paths
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananSurat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis_surat', models.CharField(choices=[('SKU', 'SKU'), ('DOMISILI', 'DOMISILI'), ('SKTM', 'SKTM')], max_length=50)),
                ('keperluan', models.TextField()),
                ('status', models.CharField(choices=[('REJECTED', 'REJECTED'), ('VERIFIED', 'VERIFIED'), ('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('DONE', 'DONE')], default='PENDING', max_length=20)),
                ('nomor_surat', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=toolbox.storage.paths.surat_pdf_upload_path)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_diajukan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'layanan_surat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LayananSuratStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=20, null=True)),
                ('status_to', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histori_status', to='layanan_administrasi.layanansurat')),
            ],
            options={
                'db_table': 'layanan_surat_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
