# Generated by Django 5.0.3 on 2026-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0002_alter_layanansurat_jenis_surat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanansurat',
            name='jenis_surat',
            field=models.CharField(choices=[('SKTM', 'SKTM'), ('DOMISILI', 'DOMISILI'), ('SKU', 'SKU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED'), ('DONE', 'DONE')], default='PENDING', max_length=20),
        ),
    ]
