# Generated by Django 5.0.3 on 2026-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0003_alter_layanansurat_jenis_surat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanansurat',
            name='jenis_surat',
            field=models.CharField(choices=[('SKU', 'SKU'), ('DOMISILI', 'DOMISILI'), ('SKTM', 'SKTM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'REJECTED'), ('VERIFIED', 'VERIFIED'), ('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('DONE', 'DONE')], default='PENDING', max_length=20),
        ),
    ]
