# Generated by Django 5.0.3 on 2026-04-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0006_alter_layanansurat_jenis_surat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanansurat',
            name='jenis_surat',
            field=models.CharField(choices=[('DOMISILI', 'DOMISILI'), ('SKTM', 'SKTM'), ('SKU', 'SKU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'PROCESSED'), ('DONE', 'DONE'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
