# Generated by Django 5.0.3 on 2026-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0007_alter_layanansurat_jenis_surat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanansurat',
            name='jenis_surat',
            field=models.CharField(choices=[('DOMISILI', 'DOMISILI'), ('SKU', 'SKU'), ('SKTM', 'SKTM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('REJECTED', 'REJECTED'), ('VERIFIED', 'VERIFIED'), ('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED')], default='PENDING', max_length=20),
        ),
    ]
