# Generated by Django 5.0.3 on 2026-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0009_alter_layanansurat_jenis_surat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('DONE', 'DONE'), ('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
    ]
