# Generated by Django 5.0.3 on 2026-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0010_alter_layanansurat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanansurat',
            name='jenis_surat',
            field=models.CharField(choices=[('SKTM', 'SKTM'), ('DOMISILI', 'DOMISILI'), ('SKU', 'SKU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PROCESSED', 'PROCESSED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('VERIFIED', 'VERIFIED')], default='PENDING', max_length=20),
        ),
    ]
