# Generated by Django 5.0.3 on 2026-04-28 13:23

import django.db.models.deletion
import django.utils.timezone
import features.layanan_administrasi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0012_alter_layanansurat_jenis_surat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode unik template, contoh: SKU, SKTM, DOMISILI.', max_length=50, unique=True)),
                ('nama', models.CharField(help_text='Nama template surat yang tampil ke admin/warga.', max_length=150)),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi singkat kegunaan template surat.', null=True)),
                ('file_template', models.FileField(help_text='File template surat dalam format .docx.', upload_to=features.layanan_administrasi.models.template_surat_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Template aktif bisa dipilih warga saat mengajukan surat.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template_surat',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='layanansurat',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=features.layanan_administrasi.models.surat_docx_upload_path),
        ),
        migrations.AlterField(
            model_name='layanansurat',
            name='jenis_surat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('REJECTED', 'REJECTED'), ('VERIFIED', 'VERIFIED'), ('DONE', 'DONE')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='layanansurat',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layanan_surat', to='layanan_administrasi.templatesurat'),
        ),
    ]
