# Generated by Django 5.0.3 on 2026-04-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_administrasi', '0013_templatesurat_layanansurat_docx_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanansurat',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('REJECTED', 'REJECTED'), ('PROCESSED', 'PROCESSED'), ('VERIFIED', 'VERIFIED')], default='PENDING', max_length=20),
        ),
    ]
