# Generated by Django 5.0.3 on 2026-04-16 12:59

import django.db.models.deletion
import django.utils.timezone
import toolbox.storage.paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananPengaduan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField()),
                ('foto_bukti', models.ImageField(blank=True, null=True, upload_to=toolbox.storage.paths.pengaduan_bukti_upload_path)),
                ('status', models.CharField(choices=[('TRIAGED', 'TRIAGED'), ('CLOSED', 'CLOSED'), ('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('IN_PROGRESS', 'IN_PROGRESS')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'layanan_pengaduan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LayananPengaduanHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_from', models.CharField(blank=True, max_length=20, null=True)),
                ('status_to', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histori_tindak_lanjut', to='pengaduan_warga.layananpengaduan')),
            ],
            options={
                'db_table': 'layanan_pengaduan_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
