# Generated by Django 5.0.3 on 2026-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan_warga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananpengaduan',
            name='status',
            field=models.CharField(choices=[('TRIAGED', 'TRIAGED'), ('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=20),
        ),
    ]
