# Generated by Django 5.0.3 on 2026-04-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan_warga', '0003_alter_layananpengaduan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananpengaduan',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('OPEN', 'OPEN'), ('TRIAGED', 'TRIAGED'), ('CLOSED', 'CLOSED'), ('IN_PROGRESS', 'IN_PROGRESS')], default='OPEN', max_length=20),
        ),
    ]
