# Generated by Django 5.0.3 on 2026-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan_warga', '0004_alter_layananpengaduan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananpengaduan',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'CLOSED'), ('RESOLVED', 'RESOLVED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('TRIAGED', 'TRIAGED'), ('OPEN', 'OPEN')], default='OPEN', max_length=20),
        ),
    ]
