# Generated by Django 5.0.3 on 2026-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan_warga', '0006_alter_layananpengaduan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananpengaduan',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('TRIAGED', 'TRIAGED')], default='OPEN', max_length=20),
        ),
    ]
