# Generated by Django 5.0.3 on 2026-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan_warga', '0007_alter_layananpengaduan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananpengaduan',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('TRIAGED', 'TRIAGED'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=20),
        ),
    ]
