# Generated by Django 5.0.3 on 2026-04-17 02:13

import django.db.models.deletion
import django.utils.timezone
import toolbox.storage.paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('sejarah', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profil_desa',
            },
        ),
        migrations.CreateModel(
            name='WilayahDusun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_dusun', models.CharField(max_length=100)),
                ('kepala_dusun', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wilayah_dusun',
            },
        ),
        migrations.CreateModel(
            name='WilayahPerangkat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=toolbox.storage.paths.perangkat_photo_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wilayah_perangkat',
            },
        ),
    ]
